# Generated by Django 4.1 on 2022-08-26 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_student_about_student_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(choices=[('TR', 'Turkey'), ('US', 'America'), ('DE', 'Germany'), ('FR', 'France')], default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
